### ISSUE TITLE
backward compatibility issue for  connection information

### ISSUE THREAD

**Issue by stoch** [K2InformaticsGmbH/dderl#113]
=ERROR REPORT==== 30-Jun-2015::18:32:54 ===
** Generic server dderl_dal terminating 
** Last message in was {add_connect,
                           {erlimem_session,<0.12659.0>},
                           {ddConn,108193735,<<"CPro Prod OLT A01">>,system,
                               imem,
                               #{<<"host">> => <<"host">>,
                                 <<"method">> => <<"local">>,
                                 <<"port">> => <<"8126">>,
                                 <<"secure">> => true,
                                 <<"user">> => <<"system">>},
                               cpro}}
** When Server state == ok
** Reason for termination == 
** {badarg,[{maps,remove,
                  [password,
                   [{ip,<<"host">>},
                    {port,<<"8126">>},
                    {type,tcp},
                    {user,<<"system">>},
                    {secure,true}]],
                  []},
            {dderl_dal,check_save_conn,4,
                       [{file,"src/dderl_dal.erl"},{line,603}]},
            {dderl_dal,handle_call,3,[{file,"src/dderl_dal.erl"},{line,396}]},
            {gen_server,try_handle_call,4,
                        [{file,"gen_server.erl"},{line,607}]},
            {gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,639}]},
            {proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,237}]}]}
18:32:54.232 [info] [_DDRL_] {dderl_dal,334} dderl_dal starting...

**Comment by c-bik** [comment]
It is agreed to fixed by manually upgrading data as and when needed
