### ISSUE TITLE
Remove user name when changing password

### ISSUE THREAD

**Issue by stoch** [K2InformaticsGmbH/dderl#115]
The GUI side (Browser) does not really know the name of the user who is connected in a given window.

That said, it should not try to display this (possibly wrong information). Guessing the user name out of the connection ownership is not valid.

![2015-07-09 17_54_00-zhhapmop-sbsm01 it bwns ch - remote desktop connection - __remote](https://cloud.githubusercontent.com/assets/1941407/8600076/48624788-2664-11e5-8fc9-74c44f59f124.jpg)
The line with the user name must disappear.

**Comment by acautin** [comment]
The user name is correctly show, when using imem if connected shows the name of the connected user else it shows the dderl account user.

The inconsistency happens when using change password from inside a oracle connection, and there is an error trying to complete the operation.
