### ISSUE TITLE
exact key search above rownum

### ISSUE THREAD

**Issue by zsoltm** [K2InformaticsGmbH/dderl#119]
When a user tries to search for a key with an "in" filter operand, the result doesn't get listed if the rownum is exceeded.

**Comment by acautin** [comment]
@stoch is this a valid issue ? can it be closed if will not be implemented ?

**Comment by acautin** [comment]
closing as this works as expected, if filtering is done on the client (fsm side) re executing the query with appropriated where clause brings the data as expected.
