### ISSUE TITLE
Aliased query columns cannot be modified in Oracle connections

### ISSUE THREAD

**Issue by stoch** [K2InformaticsGmbH/dderl#122]
![2015-09-06 16_40_07-zhhapmop-sbsm01 it bwns ch - remote desktop connection - __remote](https://cloud.githubusercontent.com/assets/1941407/9704944/1236f75a-54b6-11e5-9511-a6db769fc161.jpg)

Thsi works for IMEM connections

**Comment by acautin** [comment]
Fixed on https://github.com/K2InformaticsGmbH/dderloci/commit/1bf26bed3e0bb778858e0bea12c3323e58ba77f1
