### ISSUE TITLE
Unable to restore big tables.

### ISSUE THREAD

**Issue by acautin** [K2InformaticsGmbH/dderl#123]
trying to restore big tables results in timeout, crashing the session.

Stacktrace

=ERROR REPORT==== 8-Sep-2015::08:30:41 ===
** Generic server <0.761.0> terminating 
** Last message in was {atomic,ok}
** When Server state == {state,[{<0.785.0>,{stmt,{dderl_fsm,<0.786.0>}}}],
                               local,local,[],
                               {0,<<>>},
                               sbsgui,'$not_a_session',undefined,undefined,
                               true,'$not_a_timer'}
** Reason for termination == 
** {function_clause,[{gen_server,reply,
                                 [atomic,ok],
                                 [{file,"gen_server.erl"},{line,218}]},
                     {erlimem_session,handle_info,2,
                                      [{file,"src/erlimem_session.erl"},
                                       {line,347}]},
                     {gen_server,try_dispatch,4,
                                 [{file,"gen_server.erl"},{line,593}]},
                     {gen_server,handle_msg,5,
                                 [{file,"gen_server.erl"},{line,659}]},
                     {proc_lib,init_p_do_apply,3,
                               [{file,"proc_lib.erl"},{line,237}]}]}
08:30:41.551 [info] [_IMEM_] {imem_statement,615} received unexpected exit info from parent <0.761.0> ref #Ref<0.0.0.5056> reason {function_clause,[{gen_server,reply,[atomic,ok],[{file,"gen_server.erl"},{line,218}]},{erlimem_session,handle_info,2,[{file,"src/erlimem_session.erl"},{line,347}]},{gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,593}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,659}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,237}]}]}

**Comment by acautin** [comment]
@c-bik this seems to be an imem issue, using imem 1.3.3 restores the table in about 2 seconds. Something is making the restore process very slow for the new imem.

**Comment by c-bik** [comment]
@acautin thanks... Please continue with this work around (restoring with older version).
You can leave IMEM debugging to me if you have other priorities

**Comment by c-bik** [comment]
Observed for tpac only, which has a defective trigger installed. Fixed in https://github.com/K2InformaticsGmbH/sbsgui/commit/973a9318d561d9930702de03e1922e4671cfe532
