### ISSUE TITLE
Receive data is slow and fails for larger data volumes when copying from oracle to oracle

### ISSUE THREAD

**Issue by stoch** [K2InformaticsGmbH/dderl#130]
Can be reproduced in zhh management:

1) fill sender statement on connection sbs1.exaprod with 
select * from numberrange where rownum <= 200000
goto end
125'000 rows in buffer

2) truncate numberrange on sbs1.stag (not the other way round !!!!!!!)
open receiving statement with
select * from numberrange where rownum <= 200000

3) send data on sbs1.exaprod

4) receive data on sbs1.stag

5) check progress in SqlNavigatir on sbs1.stag using
select count(*) from numberrange

6) doing this in another statement in DDerl does not work for unknown reasons
![2015-09-27 17_21_53-zhhapmop-sbsm01 it bwns ch - remote desktop connection - __remote](https://cloud.githubusercontent.com/assets/1941407/10123537/5bbd1de6-653c-11e5-8727-c0aeb0b52e5b.jpg)

7) after 14700 rows inserted into the receiving table, the process does not continue any more

8) While copying is not progressing any more, one CPU still remains at 25% 

![2015-09-27 17_24_49-zhhapmop-sbsm01 it bwns ch - remote desktop connection - __remote](https://cloud.githubusercontent.com/assets/1941407/10123548/caca64d2-653c-11e5-8dc1-481204a8550a.jpg)

7) Even while copying correctly initially, erloci processes have negilgable CPU consumption and the erlang VM process also remains at 3% CPU. This means that time is lost somewhere in communication overhead or latency.

**Comment by acautin** [comment]
issue was on dderloci, fixed on https://github.com/K2InformaticsGmbH/dderloci/commit/825f7ad8dadfd193386cab0999d3ae3e33302229
