### ISSUE TITLE
Bad error message for request on dead connection

### ISSUE THREAD

**Issue by stoch** [K2InformaticsGmbH/dderl#135]
When a client attempts do request something on a dead session, a **warning** message like "request attempt on dead session" should be logged instead of the following:  

2015-10-23 12:24:44.847 [error] <0.18755.6>@dderl_session:get_session:76 [_DDRL_] {dderl_session,76} Eror badarg
DDerlSessionString = "xXz7CtGuKNh+KwFDULydgA0cGa8KAmkowxXYkm0/7WmDcgADZAAhc2JzZ3VpQHpoaGFwbW9zLXNic2gwMi5pdC5id25zLmNoAgADUrAAFAABAAAAALhKpmnnbKbR6OPvQrFvcKdoOs9gc46PHIPgnZVjCOiD"
[{erlang,is_process_alive,[<4200.9426.7>],[]},{dderl_session,get_session,2,[{file,"src/dderl_session.erl"},{line,68}]},{dderl_resource,process_request_low,5,[{file,"src/dderl_resource.erl"},{line,115}]},{cowboy_handler,handler_init,4,[{file,"src/cowboy_handler.erl"},{line,64}]},{cowboy_protocol,execute,4,[{file,"src/cowboy_protocol.erl"},{line,442}]}]

**Comment by shamis** [comment]
Fixed in 858728a
