### ISSUE TITLE
Double escaping of user entered JSON

### ISSUE THREAD

**Issue by zsoltm** [K2InformaticsGmbH/dderl#137]
Editing json data with escaped backslashes behaves badly with certan sequences, let's say I'd like to have a json string with the path-like value: `AppData\npm`. I enter it of course as: `AppData\\npm` as backslashes need to be escaped in JSON.

![image](https://cloud.githubusercontent.com/assets/707038/10845510/c6d16246-7f08-11e5-940e-0a9c736bb7f7.png)

After applying the changes, even before committing I see there is a problem with escaping:

![image](https://cloud.githubusercontent.com/assets/707038/10845531/dcd0dfa4-7f08-11e5-8488-7dc1901bf05f.png)

It become `{"PATH":"Appdata\\\npm"}`, an extra backslash was added. It's very unfortunate as in this particular example if I parse again this string from a database client the result would be`Appdata\<newline>pm`, a backslash follwed by an ascii 10 character as `\n` will be interpreted as newline escape sequence after the initial backslash.

**Comment by zsoltm** [comment]
@stoch please reassign this to whoever you think is suitable for.

**Comment by stoch** [comment]
@acautin 
1) if you detect that a text represents a valid JSON string, then it should not be escaped once more on the way from edit to the record buffer

2) we should allow text editing in edit window if something is not representing a valid JSON term and also not a valid Erlang term.  In that case liefeeds and whitespace should be preserved. I such a text is modified into valid JSON, it can be seen as JSON on the way back to the DB.

**Comment by acautin** [comment]
@zsoltm for now as a workaround if you need to insert AppData\\npm or similar, it has to be manually fixed on cvalue editing directly on the grid, and it will be saved correctly.
