### ISSUE TITLE
Login errors reported in unreachable window

### ISSUE THREAD

**Issue by stoch** [K2InformaticsGmbH/dderl#145]
Unsuccessful login attempts and other errors are shown in greyed-out format in the background where they can only be closed after a successful login.

![2015-12-12 10_18_13-dderl - internet explorer](https://cloud.githubusercontent.com/assets/1941407/11761237/57f53716-a0ba-11e5-9afe-a95d10a4a361.png)

Options: 
* leave in the background but clear the window automatically with a new login attempt
* paint in the foreground and let user manually close the popup if wanted

**Comment by nandapop** [comment]
@stoch  is this ok?

![image](https://cloud.githubusercontent.com/assets/8002514/14202814/717f8366-f7fa-11e5-86d5-0a68d7d74cab.png)
