### ISSUE TITLE
Change user password in dderl

### ISSUE THREAD

**Issue by c-bik** [K2InformaticsGmbH/dderl#146]
Its not needed add a new feature to generate encrypted password and then directly change ddAccount... DDErl/IMEM already provides a easy SQL based solution for this

![image](https://cloud.githubusercontent.com/assets/913008/11867096/436e345c-a4af-11e5-8b1c-844a9d0a6b31.png)

after `alter user admin  identified by abc`

![image](https://cloud.githubusercontent.com/assets/913008/11867266/4d8a3e30-a4b0-11e5-9370-06becf9b0cb8.png)

**Comment by tgdriph3** [comment]
feature is nice, hence it does not check the password complexity. Is there a way to tell the user changing the password, using alter ... that his password is weak ?

**Comment by c-bik** [comment]
The change impact for "password complexity enforcement" are in two places:

1. In IMEM (`alter user XXX identified by YYYY`) : a configurable fun in `ddConf` (`isPasswordComplex`) will be provided (default `fun(Password) when is_list(Password); is_binary(Password) -> true end`) to implement a suitable check algorithm
2. User password can also be changed through DDerl (which is md5 hashed before sent through AJAX) : a [javascript algorithm should be elected](http://www.sitepoint.com/5-bootstrap-password-strength-metercomplexity-demos/) to provide this functionality through DDerl

@tgdriph3 is this acceptable for you?

**Comment by tgdriph3** [comment]
@c-bik, yes.
1.) Please implement the fun using same algorythm that is implemented on the DDerl interface.
2.) Please choose Nr. 3

**Comment by c-bik** [comment]
IMEM part of this issue is tracked at https://github.com/K2InformaticsGmbH/imem/issues/61

**Comment by tgdriph3** [comment]
Please restrict the 'Change Password' button to be only clickable when the user reaches a "Strong" password, in that way he's forced to choose a strong password and not only addvised. ;-)

**Comment by c-bik** [comment]
@tgdriph3 **FYI** and **NOTE**

The old configuration:
```erlang
[{imem,imem_sql_account,isPasswordComplex}]
<<"
fun (Password) ->
	re:run(Password,
	       \"^(?=.{8,})(?=.*[A-Z])(?=.*[a-z])(?=.*[0-9])(?\"
	       \"=.*\\\\W).*$\")
	  /= nomatch
end
">>
```
will be **depricated/obsolidated** in the new release of DDErl and SBSGUI. It will be replaced with folowing new configuration:
```erlang
[{imem,imem_seco,passwordStrength}]
<<"
fun (Password) ->
	REStrong =
	    \"^(?=.{8,})(?=.*[A-Z])(?=.*[a-z])(?=.*[0-9])(?\"
	    \"=.*\\\\W).*$\",
	REMedium =
	    \"^(?=.{7,})(((?=.*[A-Z])(?=.*[a-z]))|((?=.*[A-\"
	    \"Z])(?=.*[0-9]))|((?=.*[a-z])(?=.*[0-9]))).*$\",
	REEnough = \"(?=.{6,}).*\",
	case re:run(Password, REEnough) of
	  nomatch -> short;
	  _ ->
	      case re:run(Password, REStrong) of
		nomatch ->
		    case re:run(Password, REMedium) of
		      nomatch -> weak;
		      _ -> medium
		    end;
		_ -> strong
	      end
	end
end
">>
```
