### ISSUE TITLE
DDerl authentication and login needs adaption to short erlimem session timeout

### ISSUE THREAD

**Issue by stoch** [K2InformaticsGmbH/dderl#150]
erlimem session times out after 5 seconds now instead of a much longer period before.

The existing DDerl authentication and login workflow is now unusable for anyone needing more than 5 seconds for typing the password.

A quick workaround (e.g. configurable erlimem timeout or linking old erlimem) may be needed to re-enable ZHH management functionality on DDerl/sbsgui master.

The DDerl login mechanism must be reworked to account for this problem. 
DDerl must bring its own and configurable login timeout control, independent of the erlimem cleanup strategy.
Care must be taken to:
* check the stability of the network parameters during the whole login process because the initial network based imem auth steps assume this for the rest of the session
* keep resource consumption low because attackers can try to simulate user logins in parallel
* support all types of authentication mechanisms and respect ther timing needs (approx. 1 minute for smsott)
* support all workflow options (e.g. abort/resume after smott validation failure)

**Comment by c-bik** [comment]
Partially Fixed : https://github.com/K2InformaticsGmbH/erlimem/issues/8

**Comment by shamis** [comment]
@c-bik, @stoch  fixed in PR https://github.com/K2InformaticsGmbH/dderl/pull/197 please verify

**Comment by c-bik** [comment]
Fixed, Verified!
