### ISSUE TITLE
DDerl Login: Button "Delete" on frontpage needs an "are you sure" confirmation

### ISSUE THREAD

**Issue by tgdriph3** [K2InformaticsGmbH/dderl#156]
Button "Delete" is hit to many times. It's action could be missunderstood. It would be good if a "are you sure" confirmation is added. What probably could be wanted by the user is a "clear" button, to empty the input-fields but leave the connections in place.

**Comment by stoch** [comment]
@c-bik 
I suggest to restrict the "Delete" function to 
* system account (for all connections)
* any account for his own connections

additionally, asking back for confirmation could be a good idea

**Comment by c-bik** [comment]
@stoch [Present implementation](https://github.com/K2InformaticsGmbH/dderl/blob/master/src/dderl_dal.erl#L225-L242) should already be doing what you are asking. Please report a bug separately if it isn't.

**Comment by acautin** [comment]
@c-bik my impression is that the validation is only about usage permissions, which should not mean the user is allowed to delete the connection or did I read it wrong ?.

```
        case Sess:run_cmd(have_permission, [{ConId, use}]) of
        true ->
            ok = Sess:run_cmd(delete, [ddConn, ConId]),
            ?Info("del_conn connection ~p deleted", [ConId]),
```

**Comment by stoch** [comment]
@c-bik The permission needed to delete a connection is

dderl_manage_conns

but a connection owned by a user can also be deleted by this user.

**Comment by stoch** [comment]
@c-bik  sorry, dderl_manage_conns is a helper role. Cannot be used inside DDErl.

The list of current helper roles, their sub-roles and permissions is:

id|roles|permissions
---|---|---
dderl_adm|[dderl_leader]|[manage_system,manage_accounts, manage_system_tables,manage_user_tables]
dderl_create_conns|[]|[{dderl,conn,create}]
dderl_leader|[dderl_manage_conns, dderl_user]|[{table,ddConn,insert},{table,ddConn,update}, {table,ddConn,delete},{table,ddDash,insert}, {table,ddDash,update},{table,ddDash,delete},{table,ddView,insert},{table,ddView,update}, {table,ddView,delete},{table,ddCmd,insert},{table,ddCmd,update},{table,ddCmd,delete},create_table]
dderl_manage_conns|[dderl_create_conns]|[{dderl,conn,manage}]
dderl_restart|[]|[{dderl,restart}]
dderl_sys_conns_use|[]|[{dderl,conn,{owner,system},use}]
dderl_user|[dderl_sys_conns_use]|[{table,ddAdapter,select},{table,ddConn,select}, {table,ddDash,select},{table,ddView,select},{table,ddCmd,select}, {table,user_tables,select},{table,all_tables,select}, {table,ddSize,select},{table,ddInterface,select}]

**Comment by c-bik** [comment]
Currently used permissions from DDerl are:
* `{dderl, restart}`
* `{dderl, conn, manage}`
* `{dderl, conn, create}`
* `{dderl, conn, {owner, system}, use}`
* `{dderl, conn, {conn, #ddConn.Id}, use}`
* `{dderl, conn, local, use}` (**NEW**)

**Comment by c-bik** [comment]
Re-opened and assigned to @stoch for installation verification and data fix

**Comment by c-bik** [comment]
@tgdriph3

![image](https://cloud.githubusercontent.com/assets/913008/12895682/efb257ee-ce9d-11e5-93b4-574ef41a22f8.png)
and
![image](https://cloud.githubusercontent.com/assets/913008/12895705/0c57a548-ce9e-11e5-9476-7773bc308dce.png)

For your review/commants.

**Comment by tgdriph3** [comment]
@c-bik : perfec! Matches my wishes 100%. Still found a small bug to be fixed.

1. login using `any user`
1. remove line in `schema` using clear
1. reenter same line in `schema`
1. boom -> see stack trace

{function_clause,[{imem_adapter,conn_method, [<<>>], [{file,"src/imem_adapter.erl"},{line,111}]}, {imem_adapter,process_cmd,6, [{file,"src/imem_adapter.erl"},{line,203}]}, {dderl_session,process_call,4, [{file,"src/dderl_session.erl"},{line,481}]}, {dderl_session,handle_cast,2, [{file,"src/dderl_session.erl"},{line,120}]}, {gen_server,try_dispatch,4, [{file,"gen_server.erl"},{line,615}]}, {gen_server,handle_msg,5, [{file,"gen_server.erl"},{line,681}]}, {proc_lib,init_p_do_apply,3, [{file,"proc_lib.erl"},{line,240}]}]}
