### ISSUE TITLE
CSV export for IMEM cursors

### ISSUE THREAD

**Issue by stoch** [K2InformaticsGmbH/dderl#164]
IMEM query data should be exportable to a csv text file.
* A file header should be written using the column headers of the query
* The default column separator should be \t
* The default line separator could be platform dependent or \r\n if it must be fixed
* The data should be drawn from the currently loaded, sorted and filtered ets buffer (no attempt to re-query using SQL).

**Comment by acautin** [comment]
#302 was a duplicated of this one and it is already implemented.
