### ISSUE TITLE
Histogram picks the wrong column after hiding other columns

### ISSUE THREAD

**Issue by stoch** [K2InformaticsGmbH/dderl#167]
@walter-weinmann Maybe you could have a look into that problem? Not urgent.

![2016-02-10 10_23_08-zhhapmop-sbsm01 it bwns ch - remote desktop connection - __remote](https://cloud.githubusercontent.com/assets/1941407/12943359/0b398cbe-cfe1-11e5-857b-911384ef2cc7.png)

**Comment by acautin** [comment]
Closed by pr #176
