### ISSUE TITLE
csv export: delimiter should be configurable

### ISSUE THREAD

**Issue by tgdriph3** [K2InformaticsGmbH/dderl#168]
... in ddConfig
per user and in general.

default should be \t (as override from ddConfig)

csvExportDelimiter
csvExportDelimiterNewLine

**Comment by c-bik** [comment]
Per adapter configurable
![image](https://cloud.githubusercontent.com/assets/913008/12987189/3d5098bc-d0fb-11e5-8e7d-86b98c41eacd.png)

**Comment by tgdriph3** [comment]
@c-bik whuhu, that was quick, thanks.
