### ISSUE TITLE
Delete view does not work

### ISSUE THREAD

**Issue by stoch** [K2InformaticsGmbH/dderl#175]
![2016-03-08 10_19_13-zhhapmop-sbsm01 it bwns ch - remote desktop connection - __remote](https://cloud.githubusercontent.com/assets/1941407/13597192/7567c07e-e517-11e5-978a-bb771bd15c23.png)

No reaction on selecting this menu option.

It would also be nice to have the view menue items available here (after pressing edit on the left pane). That would avoid the need to run the view and produce data befire one can delete or rename the view.

![2016-03-08 10_23_01-zhhapmop-sbsm01 it bwns ch - remote desktop connection - __remote](https://cloud.githubusercontent.com/assets/1941407/13597247/c96537ce-e517-11e5-966b-108ff7961cbc.png)

@walter-weinmann Maybe something for you?

**Comment by walter-weinmann** [comment]
I'll try my best.

On 8 March 2016 at 10:27, Stefan Ochsenbein <notifications@github.com>
wrote:

> [image: 2016-03-08 10_19_13-zhhapmop-sbsm01 it bwns ch - remote desktop
> connection - __remote]
> <https://cloud.githubusercontent.com/assets/1941407/13597192/7567c07e-e517-11e5-978a-bb771bd15c23.png>
>
> No reaction on selecting this menu option.
>
> It would also be nice to have the view menue items available here (after
> pressing edit on the left pane). That would avoid the need to run the view
> and produce data befire one can delete or rename the view.
>
> [image: 2016-03-08 10_23_01-zhhapmop-sbsm01 it bwns ch - remote desktop
> connection - __remote]
> <https://cloud.githubusercontent.com/assets/1941407/13597247/c96537ce-e517-11e5-966b-108ff7961cbc.png>
>
> @walter-weinmann <https://github.com/walter-weinmann> Maybe something for
> you?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/K2InformaticsGmbH/dderl/issues/175>.
>



-- 

___________________________________________________________________________
*Walter Weinmann*
___________________________________________________________________________
Obertorplatz 4
CH-4130 Rheinfelden
Tel +41 (0)61 841 06 10
___________________________________________________________________________
Schulstrasse 1
CH-6037 Root
Tel +41 (0)41 530 39 70
___________________________________________________________________________

**Comment by acautin** [comment]
Fixed on PR https://github.com/K2InformaticsGmbH/dderl/pull/182 from @walter-weinmann
