### ISSUE TITLE
bad interface to sqlparse

### ISSUE THREAD

**Issue by stoch** [K2InformaticsGmbH/dderl#183]
This line is buggy as pt_to_string() just returns a binstr with the sql text converted back from the pars tree

\git\dderl\src\dderl_fsm.erl(1318): {ok, Pt} -> sqlparse:pt_to_string(Pt);

@acautin 
Why was this not detected earlier?
What are the consequences if we correct it?

**Comment by acautin** [comment]
@stoch I don't understand how it is buggy ? if we have a parse tree we want the normalized sql query string and that is what we get from pt_to_string no ?

**Comment by stoch** [comment]
@acautin  Yes but without wrapping into an ok tuple.

**Comment by c-bik** [comment]
@acautin what @stoch means is:
```erlang
> {ok, PT} = sqlparse:parsetree("select * from tab").
{ok,[{{select,[{hints,<<>>},
               {opt,<<>>},
               {fields,[<<"*">>]},
               {into,[]},
               {from,[<<"tab">>]},
               {where,{}},
               {'hierarchical query',{}},
               {'group by',[]},
               {having,{}},
               {'order by',[]}]},
      {extra,<<>>}}]}
> sqlparse:pt_to_string(PT).
<<"select * from tab">>
```
Note its not like [`{ok, Pt} -> sqlparse:pt_to_string(Pt);`](https://github.com/K2InformaticsGmbH/dderl/blob/master/src/dderl_fsm.erl#L1318)

**Comment by acautin** [comment]
@c-bik @stoch I think you are confusing ``->`` with ``=`  we are not matching pt_to_string with {ok, Pt}.

**Comment by stoch** [comment]
@acautin  OK see it now. Sorry for disturbing.

**Comment by c-bik** [comment]
:wink: Oops!
