### ISSUE TITLE
Ui improvements.

### ISSUE THREAD

**Issue by acautin** [K2InformaticsGmbH/dderl#198]
Contribution from Gunnar at [hackergarten luzern](http://www.meetup.com/Hackergarten-Luzern/)
![datenbank_applikation-01](https://cloud.githubusercontent.com/assets/949102/14376677/39e959ba-fd6b-11e5-979a-ca72eaab2ab8.png)
![datenbank_applikation-02](https://cloud.githubusercontent.com/assets/949102/14376676/39e9128e-fd6b-11e5-92b6-c150a4b842e7.png)
![datenbank_applikation-04](https://cloud.githubusercontent.com/assets/949102/14376679/39eba418-fd6b-11e5-9ba0-56f1c465edae.png)
![dderl](https://cloud.githubusercontent.com/assets/8002514/14379886/d8181796-fd7c-11e5-8302-9ea6c5229a36.png)

**Comment by acautin** [comment]
This needs jquery ui 1.11+ for icons on the dialogs. Blocked at the moment by https://github.com/K2InformaticsGmbH/dderl/issues/100

**Comment by nandapop** [comment]
Improvement on sort dialog

![image](https://cloud.githubusercontent.com/assets/8002514/14489359/f76ed5a0-016c-11e6-8a41-ab3670f9c200.png)
