### ISSUE TITLE
Edit error unnecessary and missing icon

### ISSUE THREAD

**Issue by c-bik** [K2InformaticsGmbH/dderl#224]
![image](https://cloud.githubusercontent.com/assets/913008/14665834/442cbde4-06d6-11e6-9b4f-9daa1ec59ef7.png)

![image](https://cloud.githubusercontent.com/assets/913008/14665873/8563bce0-06d6-11e6-81ad-7c046305a3f5.png)

**Comment by acautin** [comment]
Icon missing.

**Comment by nandapop** [comment]
Fixed 👍 
2a6a46655dde5d8111bdde2ca91e38be635c07a6

**Comment by c-bik** [comment]
Still error dialogs!

**Comment by acautin** [comment]
@c-bik I was unable to reproduce the error dialogs anymore, did you remeber to ``brunch build`` dderl ? @shamis please confirm.

**Comment by shamis** [comment]
@acautin Ya this is a different scenario. It when you are editing text. not erlang term nor json.

**Comment by acautin** [comment]
@shamis this should be fixed now, right ?

**Comment by c-bik** [comment]
Verified!
