### ISSUE TITLE
Style support for DDerl

### ISSUE THREAD

**Issue by tgdriph3** [K2InformaticsGmbH/dderl#228]
First of all, big Kudos to everyone that was Hackergarten and improved DDerl to what it is now on management station. They anoying bug of 'moving buttons on closing window' is finally banned. Moreover minimizing of windows to a bottom bar is included as a new feature even before I had the time to place it as a wish - fantastic!

Still I noticed something while working with the new version:

1.) I do spent much more time doing my work / trying to get arround in DDerl

Why is this, I think the black / bold color of the toolbar + buttons distract me too much and my eyes keep changing the focus to the lower part of the screen instead of stay focused on the data (which is in some times not easy :).

Therefore I would request the old look & feel to come back. Is it possible to add the new look & feel as a style and keep the old style as default ? Style support has been 'wished' by operation anyway some of them even want colored buttons (search for peace colors in google...).

**Comment by acautin** [comment]
@tgdriph3 thanks for the feedback, @c-bik created an issue with suggestions for improvements #230 , I think keeping the old gray default with highlighting would solve this problem. Closing this one as duplicated.
