### ISSUE TITLE
ssl protocol version switch trough erlang VM (attach) for dderl modul

### ISSUE THREAD

**Issue by tgdriph3** [K2InformaticsGmbH/dderl#231]
VM shall provide following three functions on dderl modul:
```
list getSupportedSSLProtocols()
boolean setSSLProtocols(list)
list getSSLProtocols()
```
setter should return false if operation was not successfull of if list is null or contains any invalid options and return without change. If possible a message shall be issues after every set "PLEASE RESTART SERVICE..."

setter should not underly any restriction, so even ssl3 shall be allowed, hence ssl3 shall still be deactivated on dderl startup

**Comment by c-bik** [comment]
No practical need identified!
