### ISSUE TITLE
Timeout with histogram on csv table

### ISSUE THREAD

**Issue by stoch** [K2InformaticsGmbH/dderl#238]
logTime	logLevel	pid	module	function	line	node	fields	message	stacktrace
03.05.2016 14:08:39.963829	error	<0.21330.17>	dderl_session	spawn_gen_process_call	573	'sbsgui@ZHHAPMOP-SBSM01.it.bwns.ch'	[]	Problem processing command: exit:{timeout,{gen_fsm,sync_send_all_state_event,[<0.21295.17>,{histogram,"\n"}]}}\n[{gen_fsm,sync_send_all_state_event,2,[{file,"gen_fsm.erl"},{line,249}]},{gen_adapter,process_cmd,6,[{file,"src/gen_adapter.erl"},{line,244}]},{dderl_session,spawn_gen_process_call,7,[{file,"src/dderl_session.erl"},{line,571}]}]	[{gen_fsm,sync_send_all_state_event,2,[{file,"gen_fsm.erl"},{line,249}]},{gen_adapter,process_cmd,6,[{file,"src/gen_adapter.erl"},{line,244}]},{dderl_session,spawn_gen_process_call,7,[{file,"src/dderl_session.erl"},{line,571}]}]

happens when trying to histogram nearly 10000 distinct values in col7 of this query:

select
    file
    ,
    offset
    ,
    bytes
    ,
    col1
    ,
    col2
    ,
    col3
    ,
    col4
    ,
    col5
    ,
    col6
    ,
    col7
    ,
    col8
  from
    csv$tab."D:\\Temp\UCP-51.txt"

![image](https://cloud.githubusercontent.com/assets/1941407/14982810/67dfc336-1139-11e6-83e2-b36682a8fdb8.png)

1000 distinct values works

@walter-weinmann Do you have an idea?

**Comment by walter-weinmann** [comment]
**`dderl_fsm.erl line 270:`**

Perhaps we should use 

``` erlang
-spec get_histogram(pos_integer(), {atom(), pid()}) -> [tuple()].
get_histogram(ColumnId, {?MODULE, Pid}) ->
    gen_fsm:sync_send_all_state_event(Pid, {histogram, ColumnId}, infinity).
```

or an appropriate timeout value?

Unfortunately my system environment doesn't include appropriate test data - I suppose.
