### ISSUE TITLE
DDerl views should include d3 graph defnitions in its viewstate

### ISSUE THREAD

**Issue by acautin** [K2InformaticsGmbH/dderl#243]
Sample of View state which needs to be supported (for one single graph with script placeholder), relevant new fields: 
- **plane_to_show**: Represents the default graph to be shown when the the view is open via the ``Browse Data`` command, from 1 to ``length( plane_specs)`` show graph, otherwise show slickgrid data
- **plane_specs**: Object representing the definition of a d3 graph

```
{viewstate
,[{<<"width">>,1285}
 ,{<<"height">>,130}
 ,{<<"y">>,129}
 ,{<<"x">>,28}
 ,{<<"plane_to_show">>,0}
, {<<"plane_specs">>,[[{<<"script">>,<<"D3 HTML Script code goes here">>}]]}
 ]
,[[{<<"name">>,<<"id_1">>}
  ,{<<"width">>,108}
  ,{<<"hidden">>,false}
  ]
 ,[{<<"name">>,<<"roles_2">>}
  ,{<<"width">>,152}
  ,{<<"hidden">>,false}
  ]
 ,[{<<"name">>,<<"permissions_3">>}
  ,{<<"width">>,1000}
  ,{<<"hidden">>,false}
  ]
 ,[{<<"name">>,<<"quotas_4">>}
  ,{<<"width">>,61}
  ,{<<"hidden">>,false}
  ]
 ]
}
```

**Comment by stoch** [comment]
Sample of View state which needs to be supported (for one single graph with script placeholder)::

`{viewstate
,[{<<"width">>,1285}
 ,{<<"height">>,130}
 ,{<<"y">>,129}
 ,{<<"x">>,28}
 ,{<<"plane_to_show">>,0}
, {<<"plane_specs">>,[[{"script",<<"D3 HTML Script code goes here">>}]]}
 ]
,[[{<<"name">>,<<"id_1">>}
  ,{<<"width">>,108}
  ,{<<"hidden">>,false}
  ]
 ,[{<<"name">>,<<"roles_2">>}
  ,{<<"width">>,152}
  ,{<<"hidden">>,false}
  ]
 ,[{<<"name">>,<<"permissions_3">>}
  ,{<<"width">>,1000}
  ,{<<"hidden">>,false}
  ]
 ,[{<<"name">>,<<"quotas_4">>}
  ,{<<"width">>,61}
  ,{<<"hidden">>,false}
  ]
 ]
}`
