### ISSUE TITLE
Cannot update MAPPING table on SBS0.STAG

### ISSUE THREAD

**Issue by stoch** [K2InformaticsGmbH/dderl#248]
![image](https://cloud.githubusercontent.com/assets/1941407/15117406/b1167ad6-1607-11e6-8454-5e0d2542e6be.png)

**Comment by acautin** [comment]
Issue was fixed on https://github.com/K2InformaticsGmbH/dderloci/commit/3ed84ec8b15526059e06efdd5ccba5ca9355d676
