### ISSUE TITLE
Cannot update MAPPING table on SBS0.STAG

### ISSUE THREAD

**Issue by stoch** [K2InformaticsGmbH/dderl#249]
![image](https://cloud.githubusercontent.com/assets/1941407/15117660/d859c3b8-1608-11e6-8552-5ef704193db6.png)

**Comment by c-bik** [comment]
@stoch 
"Ungültiges Zeichen" (ORA-0091) can be a query problem:
http://www.techonthenet.com/oracle/errors/ora00911.php

Not a DDErl problem.

**Comment by c-bik** [comment]
Not a DDErl issue!
