### ISSUE TITLE
Erlang term editor swallows list items

### ISSUE THREAD

**Issue by stoch** [K2InformaticsGmbH/dderl#251]
![image](https://cloud.githubusercontent.com/assets/1941407/15192452/8b63b8b8-17b9-11e6-97b3-769c2194c4e0.png)

after removing the blue term and saving the row, the binstring key comes back.

**Comment by acautin** [comment]
@stoch I was unable to reproduce this locally.

**Comment by c-bik** [comment]
Not reproduced and not followed up!
