### ISSUE TITLE
Connection dialog should bring connections in alphabetical order.

### ISSUE THREAD

**Issue by acautin** [K2InformaticsGmbH/dderl#277]
Observed in chrome.

**Comment by acautin** [comment]
@stoch I am not able to reproduce the problem, however I have seen that uppercase letters are sorted before lowercase letters due to their ascii value. Should we sort the connections using a case insensitive comparison ? or was this related to something else.

**Comment by stoch** [comment]
![image](https://cloud.githubusercontent.com/assets/1941407/17507003/6a4dfcac-5e0d-11e6-88b8-f4ae2e74ef3d.png)

Seen in Chrome on ZHH management Version 1.6.1
