### ISSUE TITLE
DDErl session handling security improvements

### ISSUE THREAD

**Issue by c-bik** [K2InformaticsGmbH/dderl#281]
Multiple security issues has been detected in DDerl Session establishment and maintenance.
Some of them are given below:
* Session hijack
* Script injection
* XSRF
...etc

In order to close these security vulnerabilities existing session handling mechanism must be replaced with advanced secure techniques and best-practices like.

- [ ] HTTP-Only cookies
- [ ] XSRF token

...etc.

The impact on code change is non-trivial and is of currently lower priority.

cc @tgdriph3 and @stoch for review and comments

**Comment by acautin** [comment]
already implemented.
