### ISSUE TITLE
CSV Export should dump the buffer

### ISSUE THREAD

**Issue by stoch** [K2InformaticsGmbH/dderl#302]
The current CSV Export tries do do the export in streaming mode, re-executing the query and dumping fetch blocks into the file.
This mechanism is 
* inefficient if the query is slow
* inflexible because sort and filter are ignored in the output
* we cannot easily split into distinct exports by using different filters
* does not allow to export the current sample rowset only (without re-querying with a row limit)

Since the size of the export seems to be limited to 35 MBytes anyways, the last remaining argument for streaming export fails.

Please convert the default export mechanism in DDerl to a simple dump from the (sorted and filtered) view buffer.

If possible, keep the current streaming version as an Erlang command line alternative.

**Comment by acautin** [comment]
Proposed to keep the current implementation and add a new option to download the buffer.
