### ISSUE TITLE
SQL Editor issues

### ISSUE THREAD

**Issue by stoch** [K2InformaticsGmbH/dderl#31]
Choosing from SQL-History sometimes replaces the Pretty SQL string but not always (maybe depending on NewQuery/BrowseData).
It does not change the Flat SQL.
Changes in Box are not promoted to Pretty nor Flat when changing the view.
It is ok that the current SQL is not shown in the history but it should be saved before another version from the history replaces it.

SQL history drop down should auto-extend to the end of the footer line.

History should persist on a combination of SQL-window and ist associated table.

**Comment by acautin** [comment]
all but sql box is fixed, sql box needs design review so closing this issue.
