### ISSUE TITLE
Parameter Parser Duplicates for Oracle Queries

### ISSUE THREAD

**Issue by stoch** [K2InformaticsGmbH/dderl#322]
![image](https://cloud.githubusercontent.com/assets/1941407/20029627/3acdd928-a351-11e6-931c-4d3ffd4a7483.png)

observed in the MTRAC query  SQL_SMS_R

...
where
    bdcuc.ROWID = bci_rowid 
    and
    ROWNUM <= 5 * :SQLT_INT_ROWLIMIT 
    and
    bci_submitdate >= :SQLT_DAT_START_DATE 
    and
    bci_submitdate <= :SQLT_DAT_END_DATE 
    and
      (
        bc_trycount in(0,1,2,3,5,9) 
        or
        bc_status in(4,5,16) 
      )
    and
      bc_msisdn_a like :SQLT_STR_SENDER 
    and
    bci_msisdn = :SQLT_STR_RECEIVER 
    and
      (
        :SQLT_STR_SHORTID is null 
        or
          BC_CONSOL like :SQLT_STR_SHORTID 
      )
    and
      (
        :SQLT_STR_GENERATED is null 
        or
            NVL(BC_GENERATED,0) 
          like
          :SQLT_STR_GENERATED
      )

**Comment by c-bik** [comment]
Reopened for sqlparse based integration as a better solution
