### ISSUE TITLE
SQL Parsing fails

### ISSUE THREAD

**Issue by stoch** [K2InformaticsGmbH/dderl#338]
fixes #337 

SQL does not parse any more, probably since attempt to detect database link @ in table name

```sql
select *
from
    SIS_DS_ADMIN.TAB_MOBILE@SIS.EXASTAG.PIOSCS
  where
    DMO_MSISDN >= :SQLT_STR_MSISDN 
    and
    DMO_MSISDN <= :SQLT_STR_MSISDN_2 
```

**Comment by acautin** [comment]
@stoch it works if you add quotes to table name.

**Comment by stoch** [comment]
Quotes around the whole name are not tolerated by Oracle (name too long) but this works: 

select * 
from
    SIS_DS_ADMIN.TAB_MOBILE@ "SIS.EXASTAG.PIOSCS"
 where
    DMO_MSISDN >= :SQLT_STR_MSISDN 
    and
    DMO_MSISDN <= :SQLT_STR_MSISDN_2 

@c-bik Question: Can we support fully qualified DB link names without quotes?

**Comment by c-bik** [comment]
@stoch It seems #338 and #337 are now reduced into "DBLink support in sqlparse". Can you please close these issues in DDerl and transfer into one relevant issue in sqlparse?

**Comment by acautin** [comment]
@c-bik #337 is a problem with the fallback regexp in dderl as it is taking the ``>=`` as part of the parameter name. This one I will move to sqlparse.
