### ISSUE TITLE
Bring back query from query history 

### ISSUE THREAD

**Issue by stoch** [K2InformaticsGmbH/dderl#352]
![image](https://cloud.githubusercontent.com/assets/1941407/21588879/74bb123c-d0eb-11e6-8b35-aa80b2b938c8.png)

Clicking on the blue query should bring back this query into the query editor (after saving the current query on top of the history stack if not already there).

**Comment by acautin** [comment]
@stoch is the issue here: queries are not saved in the history if they are not executed ?.

Or was this query not brought back on selection ?.

**Comment by acautin** [comment]
Not able to reproduce, will remove the milestone for now and close next milestone if it doesn't appear again.

**Comment by acautin** [comment]
closing as unable to reproduce
