### ISSUE TITLE
DDerl should be less conservative when logging out.

### ISSUE THREAD

**Issue by acautin** [K2InformaticsGmbH/dderl#360]
It should try to ping the server and there is no successful response or server is down is should clean up and bring login page without prompting the user.

**Comment by acautin** [comment]
This should also apply when user is trying to close a tab and session is gone or connection to oracle was lost.

**Comment by c-bik** [comment]
Perhaps no straight forward solution exists. Need more analysis and an alternate solution

**Comment by acautin** [comment]
Closing as this is not possible to do due to browser security preventing to execute ajax calls when closing a tab.
