### ISSUE TITLE
Personalized csv export preferences

### ISSUE THREAD

**Issue by stoch** [K2InformaticsGmbH/dderl#361]
The currently available ddConfig options for csv export 
* [{dderl,gen_adapter,csvExportDelimiter}]	";"
* [{dderl,gen_adapter,csvExportDelimiterNewLine}]	"\n"

should be extended by
* [{dderl,gen_adapter,csvExportEncoding}]	utf8
* [{dderl,gen_adapter,csvExportBomPrefix}]	<<>>

and generalized in the sense that the user id is part of the context.

Also, the escaping must include the chosen field separator.

Open discussion: when do we need to escape the " character

**Comment by stoch** [comment]
Looked into the EXCEL way of doing the copy (not export):

![image](https://cloud.githubusercontent.com/assets/1941407/22067605/4a029ea8-dd92-11e6-8dcf-fe245443914e.png)
![image](https://cloud.githubusercontent.com/assets/1941407/22068058/0d4155de-dd94-11e6-92ad-d778a96604da.png)

and pasting it into textpad:

![image](https://cloud.githubusercontent.com/assets/1941407/22067576/27bc5de8-dd92-11e6-8b9c-2108c09a6249.png)
![image](https://cloud.githubusercontent.com/assets/1941407/22068093/2b5b68fc-dd94-11e6-8a9a-00ce70777de2.png)

and saving the textpad file:

![image](https://cloud.githubusercontent.com/assets/1941407/22067035/d3d6eb5a-dd8f-11e6-8d40-bddb2c0a2333.png)
![image](https://cloud.githubusercontent.com/assets/1941407/22067672/86f4f6d0-dd92-11e6-8c79-0c16d96498cf.png)
![image](https://cloud.githubusercontent.com/assets/1941407/22068140/56c3e8c0-dd94-11e6-8649-04a7fc1ba36a.png)

Interpretation: 
In Excel, the first " typed is seen (and rembered) as a 'left align' marker, meaning "the following is to be formatted left aligned to the cell". The marker is shown in the edit window but not considered part of the value (numbers are still numbers when left-aligned with a single or double quote.

No escaping or wrapping is done just because of double quotes in the cells.

I did not find a quick way to enter tab characters into the Excel cells

Putting line feeds into the cell wraps the text in double quotes and escapes double quotes inside the text correspondingly.

Now, saving as csv is another story. What I get from the Excel is this (opened in Textpad):

![image](https://cloud.githubusercontent.com/assets/1941407/22068417/3ea90dd2-dd95-11e6-8f7f-6c9f873060fb.png)

Excel is escaping all fields which have double quotes.

The way it is done in DDerl now, we can copy correctly to Excel because Erlang paste respects the escaping (while GIThub issue tracker does not)
"/saml" in DDerl becomes """/saml""" in Github (where it should not be 'corrected' if we want to paste it back to DDerl.

@c-bik Should we have wrap-escape of double quotes only in CSV export but not in Copy (as windows  does)?

Of course, wrap-escape is needed for Cr, Lf and the field separator in both outputs.

**Comment by c-bik** [comment]
@stoch 
> The way it is done in DDerl now, we can copy correctly to Excel because Erlang paste respects the escaping (while GIThub issue tracker does not)
"/saml" in DDerl becomes """/saml""" in Github (where it should not be 'corrected' if we want to paste it back to DDerl.

Pasting back to DDErl properly detects and unescapes any escaped double quote already. So that isn't any concern anymore (ref #357)
![image](https://cloud.githubusercontent.com/assets/913008/22018838/1b4f7e32-dcb1-11e6-8058-663a3f7eaaed.png)

Escaped double quotes are only visible in text editors (which can't be avoided if cell also contains need-to-escape characters).
