### ISSUE TITLE
Cannot save query

### ISSUE THREAD

**Issue by stoch** [K2InformaticsGmbH/dderl#374]
The following query cannot be saved into the view:
`select
    HIH_ID
    ,
    HIH_SRCTYPE
    ,
    HIH_MAPID
    ,
    HIH_DATETIME
    ,
    HIH_FILENAME
    ,
    86400*(SYSDATE-HIH_DATETIME) DELAY
    ,
    HIH_EXE
    ,
    HIH_VERSION
    ,
    HIH_JOB
    ,
    HIH_HOST
  from
    SBS0_ADMIN.HIHEADER
  where
    HIH_SRCTYPE <> 'STAN' 
    and
    HIH_ESID = 'MAP' 
    and
    HIH_DATETIME >= sysdate - 1 / 24 
  order by
    HIH_START desc`

It is sometimes (with a query change) corrupted into

`select
    HIH_ID
    ,
    HIH_SRCTYPE
    ,
    HIH_MAPID
    ,
    HIH_DATETIME
    ,
    HIH_FILENAME
    ,
    DELAY
    ,
    HIH_EXE
    ,
    HIH_VERSION
    ,
    HIH_JOB
    ,
    HIH_HOST
  from
    SBS0_ADMIN.HIHEADER
  where
    HIH_ESID = 'MAP' 
    and
    HIH_DATETIME >= sysdate - 1 / 24 
  order by
    HIH_START desc`

**Comment by acautin** [comment]
@stoch I am looking into it a workaround you could save the view on the editor before executing it, it was introduced by the fix to https://github.com/K2InformaticsGmbH/dderl/issues/347
