### ISSUE TITLE
Cannot connect to remote DDerl cluster

### ISSUE THREAD

**Issue by stoch** [K2InformaticsGmbH/dderl#375]
Logged in to  CPro ZHH01 prod and wanting to open a TCP DDerl connection to CPro ZHH01 stag:
Connection works but connection is to prod (local connection) instead of staging (remote TCP connection).

@acautin Could this be a consequence of latest DDerl changes?

**Comment by acautin** [comment]
@stoch what query are you using to verify is local vs remote connection ? ``All ddViews`` view is always taken from local connection. Maybe that where the confusion arises ?

**Comment by acautin** [comment]
Closing as it is is working as currently design. Filed for investigation https://github.com/K2InformaticsGmbH/dderl/issues/378
