### ISSUE TITLE
Parse numbers with apostrophe thousands separator in default D3 chart

### ISSUE THREAD

**Issue by stoch** [K2InformaticsGmbH/dderl#392]
@acautin please bring this into master before the March build 

please verify that the version of  x-y12-chart-autoscale.js in d3_examples is 'better' than the version in d3_templates (it probably is). They both should be the same and augmented with automatic deletion of apostrophes (e.g. with split/join) in an overloaded version of parseFloat (which should be used everywhere in the script).

Probably, it makes sense to also offer a similar wrapper for parseInt which could be patched in for speed if needed. DDerl today only renders integers with apostrophes (not floats), but that can change.

**Comment by acautin** [comment]
@stoch just to confirm I understood this right, I will create parse(Int|Float) wrappers on dderl graph and expose them via the helper object so they are available to all the D3 graphs, adapting the `` x-y12-chart-autoscale.js`` template/example to use this function.

**Comment by stoch** [comment]
confirmed
thanks
