### ISSUE TITLE
npm run build doesn't work from windows CMD

### ISSUE THREAD

**Issue by c-bik** [K2InformaticsGmbH/dderl#405]
["rm -rf public"](https://github.com/K2InformaticsGmbH/dderl/blob/master/priv/package.json#L42)
![image](https://cloud.githubusercontent.com/assets/913008/24307484/a4574362-10c4-11e7-8847-1465375001e6.png)

`rm` is NIX* command not supported in windows

**Comment by walter-weinmann** [comment]
can we use the following:

```
del /s /q .svn
rmdir /s /q .svn

```
/q disables Yes/No prompting

/s means delete the file(s) from all subdirectories.

**Comment by acautin** [comment]
@walter-weinmann ``del`` doesn't work on linux/OS X.
@c-bik I found https://www.npmjs.com/package/rimraf which should solve the issue, will give it a try.

**Comment by acautin** [comment]
@c-bik just remember to execute ``npm install`` after pull it fetches the new package.

**Comment by c-bik** [comment]
@acautin tested in windows cmd... works like a charm!
@walter-weinmann can you also verify/confirm?

**Comment by walter-weinmann** [comment]
It's fine for me.
