### ISSUE TITLE
Too much vertical spacing

### ISSUE THREAD

**Issue by c-bik** [K2InformaticsGmbH/dderl#426]
![image](https://cloud.githubusercontent.com/assets/913008/25521805/47eb0002-2c01-11e7-9dc2-f5b7f134d39b.png)

used to be...

![image](https://cloud.githubusercontent.com/assets/913008/25521908/9fa2396e-2c01-11e7-9d89-c1a34e5d17fd.png)

**Comment by acautin** [comment]
@c-bik which browser are you using? and some steps in particular? I was unable to reproduce filtering on firefox, chrome and IE 11.

**Comment by c-bik** [comment]
@acautin
Browser: Chrome (Version 59.0.3071.29 (Official Build) beta (64-bit)) in Windows 10
No special steps (just start DDerl and filter... window on any table)
Clearing browser cache or Incognito Window didn't help!

**Comment by acautin** [comment]
@c-bik, that browser says beta, maybe something messed up there, or it could be Windows 10 sadly I don't have access to it.

**Comment by c-bik** [comment]
@acautin 
seems like its ok with Edge:
![image](https://cloud.githubusercontent.com/assets/913008/25528676/4996e7ea-2c1f-11e7-910e-1d8ad94873bc.png)

If you can confirm with ZHH Mgmt, I will then close this issue.

**Comment by acautin** [comment]
@c-bik confirmed in Zhh
