### ISSUE TITLE
access logger - proxy field is set to no always

### ISSUE THREAD

**Issue by shamis** [K2InformaticsGmbH/dderl#450]
### Current Issue
When remote IP is proxy the 'proxy' field should to be `yes` in dderl access log file.
Currently its set to `no` all the time since configured proxy IP isn't known to the [following code snippet](https://github.com/K2InformaticsGmbH/dderl/blob/master/src/dderl_access_logger.erl#L41-L46) which helps in logging:
```erlang
proxy(Access) ->
    SrcIp = maps:get(src, Access, ""),
    case maps:get(proxy, Access, "") of
        SrcIp -> "yes";
        _ -> "no"
end.
```
### Root Cause
The proxy IP address is directly configured within `authenticateRequireFun` (in `ddConfig`) as follows (example):
```erlang
fun (Factors, NetCtx) ->
	case NetCtx of
	  #{tcp := #{peerip := {1, 2, 3, 4}}} ->
	      [saml, pwdmd5, smsott];
	  _ -> [pwdmd5]
	end
	  -- Factors
end
```
`authenticateRequireFun` (configuration) is [used in imem](https://github.com/K2InformaticsGmbH/imem/blob/42fbbb77ef9a25c90b5ceffc61874a5bd0941ad8/src/imem_seco.erl#L622) in [auth_step](https://github.com/K2InformaticsGmbH/imem/blob/42fbbb77ef9a25c90b5ceffc61874a5bd0941ad8/src/imem_seco.erl#L558)  and [auth_step_succeed](https://github.com/K2InformaticsGmbH/imem/blob/42fbbb77ef9a25c90b5ceffc61874a5bd0941ad8/src/imem_seco.erl#L639)

**Comment by c-bik** [comment]
@shamis 

A new feature of `imem_config` to read any configuration (if exists) or return error (if doesn't exists) will help to simplify the solution.
A `imem_config:val(Key :: any()) -> {ok, Val} | {error, Error}`  should be implemented, exported and declared ` safe` for this purpose.

_**this new API (`imem_config:val/1`) can have other useful applications in future**_

With this above feature available in imem, a proposed solution can be:
* New `authenticateRequireFun` (in `ddConfig`)
```erlang
fun (Factors, NetCtx) ->
        case imem_config:val(proxyIp) of
            {ok, ProxyIP} ->
                case NetCtx of
                    #{tcp := #{peerip := ProxyIP}} -> [saml, pwdmd5, smsott];
                    _ -> [pwdmd5]
                end;
            _ -> [pwdmd5]
        end -- Factors
end
```
* New `ddConfig` entry: key = `proxyIp` value = `{W.X.Y.Z}`
* Now `proxy` property can be to ` Access` map (below) from `dderl_session` (when created) with a similar `imem_config:val(proxyIp)` lookup and compare
```erlang
proxy(Access) ->
    SrcIp = maps:get(src, Access, ""),
    case maps:get(proxy, Access, "") of
        SrcIp -> "yes";
        _ -> "no"
end.
```

@stoch please comment on this new proposed feature and solution
