### ISSUE TITLE
Handling of ping after dderl crash/stopping

### ISSUE THREAD

**Issue by stoch** [K2InformaticsGmbH/dderl#489]
After killing egambo and restarting, I got

```
20:56:40.080 [info] Application egambo started on node 'egambo1@127.0.0.1'
20:56:40.143 [error] CRASH REPORT Process <0.883.0> with 0 neighbours crashed with reason: no match of right hand value {error,closed} in cowboy_http2:preface/1 line 198
20:56:40.143 [error] Ranch listener https terminated with reason: no match of right hand value {error,closed} in cowboy_http2:preface/1 line 198
20:56:40.190 [info] [_DDRL_] {dderl_resource,112} [[<<"ping">>]] session <<"FYatZtbnHUtZdZqmVix0dR/9BsibAlBuvM26JUW3Z93xQQMoHTNEI11YJkeRKlwyrtfF0cHMqtDcocYKVjaSSg==">> doesn't exist (<<"process not found">>), from 127.0.0.1:52890
```

@c-bik Is that correct or should we explicitly handle orphan pings?

**Comment by c-bik** [comment]
@stoch this is correct if you notice that orphan ping is actually handled gracefully since it is an info log.

The CRASH REPORT is from cowboy 2.x. Which related to http2 and not related to ping!

@shamis, I think, is already aware of this cowboy 2.x crash in other cases as well and is currently being ignored since it doesn’t effect DDErl operation to knowledge.

**Comment by shamis** [comment]
@stoch, @c-bik  is correct. When we get a ping with wrong session id (session pid not found) we return error with message session not valid. So the last line in the logs above is just a log saying we got a ping from a dead session. The other two lines have been seen when the service is started. There are two issues in cowboy https://github.com/ninenines/cowboy/issues/1144 and https://github.com/ninenines/cowboy/issues/806. Loic says these dont cause any harm and they just annoying log messages. Have noticed this only when the server is started. It does not happen anytime after that.
