### ISSUE TITLE
Oracle binary formatted error message

### ISSUE THREAD

**Issue by stoch** [K2InformaticsGmbH/dderl#509]
I see

{error,{error,{3113, <<79,82,65,45,48,51,49,49,51,58,32,85,110,101,114,119,97,114, 116,101,116,101,115,32,195,156,98,101,114,116,114,97,103, 117,110,103,115,101,110,100,101,32,105,110,32,75,111,109, 109,117,110,105,107,97,116,105,111,110,10,80,114,111,122, 101,115,115,45,73,68,58,32,54,53,53,53,48,10,83,101,115, 115,105,111,110,45,73,68,58,32,53,49,52,32,83,101,114,105, 101,110,110,117,109,109,101,114,58,32,52,48,56,52,54,10>>}}}

for this 

![image](https://user-images.githubusercontent.com/1941407/39247265-33dc4098-4899-11e8-92eb-def6fd5acec8.png)

SELECT * 
FROM TABLE(DBSS.IO.FILE_READ_LOG (
  :SQLT_STR_DIRECTORY,
  :SQLT_STR_FILE_NAME
))

**Comment by walter-weinmann** [comment]
von sqlparse:

sqlparse_adhoc_test : ===========================================>     Input statement(s):

```
SELECT *
FROM TABLE(DBSS.IO.FILE_READ_LOG (
:SQLT_STR_DIRECTORY,
:SQLT_STR_FILE_NAME
))

```


sqlparse_adhoc_test : -------------------------------------------> Statement catch reason:
```
{badmatch,{parse_error,{"2: syntax error before: 'TABLE'",
                        [{'SELECT',1},
                         {'*',1},
                         {'FROM',2},
                         {'TABLE',2},
                         {'(',2},
                         {'NAME',4,"DBSS"},
                         {'.',2},
                         {'NAME',2,"IO"},
                         {'.',2},
                         {'NAME',13,"FILE_READ_LOG"},
                         {'(',2},
                         {'PARAMETER',3,":SQLT_STR_DIRECTORY"},
                         {',',3},
                         {'PARAMETER',4,":SQLT_STR_FILE_NAME"},
                         {')',5},
                         {')',5},
                         {';',5}]}}}

```
Keyword `TABLE` is not allowed here.

**Comment by stoch** [comment]
@walter-weinmann 
wir werden das wohl so brauchen für Pipelining von collections von einem Workflow-Task zum anderen.
Der Issue ist aber eigentlich für das Error-Message-Formattingproblem gedacht.
