### ISSUE TITLE
Login button remains greyed out after login failed because of crash

### ISSUE THREAD

**Issue by seanhinde** [K2InformaticsGmbH/dderl#513]
Re-producible by starting dderl without INSTANT_CLIENT_LIB_PATH pointing to the libs

**Comment by stoch** [comment]
@acautin, @c-bik  Is this a build issue which should be addressed before the upcoming build?

**Comment by c-bik** [comment]
@stoch No, I think its a development setup issue. MSI doesn't depends / chesks on INSTANT_CLIENT_LIB_PATH env variable

**Comment by stoch** [comment]
But that should manifest at link time, shouldn't it?

**Comment by seanhinde** [comment]
For me at least it was my dev setup

**Comment by acautin** [comment]
This is a generic problem with our connect dialog, when connect is pressed, it will be disabled so you don't accidentally open a connection twice, if the connection fails for a crash in the server then an error is displayed but the button is never enabled.
Refreshing the page allows you to try again

**Comment by acautin** [comment]
![screen shot 2018-05-03 at 13 34 24](https://user-images.githubusercontent.com/949102/39574256-bce6ff66-4ed6-11e8-85e4-de5e367c6f4d.png)
Added image for reference.

**Comment by c-bik** [comment]
@acautin 
> Refreshing the page allows you to try again

Can we re-enable the button after/with error message displayed?
This would save a browser refresh!

**Comment by acautin** [comment]
@c-bik sure we can! this is not the expected behaviour and it is the case when errors are not the result of a server crash for example wrong password / no listener / timeout etc. This is a bug.
