### ISSUE TITLE
DDerl should allow logging of successfully executed SQL statements

### ISSUE THREAD

**Issue by stoch** [K2InformaticsGmbH/dderl#522]
Two new ddConfig entries 
```[{dderl,???,logSqlRequest}]``` of type boolean
```[{dderl,???,logSqlBind}]``` of type boolean
with context UserId and default true should determine if successfully executed SQL statements / Bind Values should be logged in the dderlLog table.
Failed sql execution should be logged already in any case, including bind parameters (to be verified).

**Comment by c-bik** [comment]
@stoch `default true` is a bad idea!

Please change it to default false! Its is flooding logs!

**Comment by c-bik** [comment]
👍 @acautin
