### ISSUE TITLE
Trailing semicolon not properly handled

### ISSUE THREAD

**Issue by stoch** [K2InformaticsGmbH/dderl#545]
The following query does not work:

![image](https://user-images.githubusercontent.com/1941407/45101129-1cd17800-b12b-11e8-8ba5-124a7de0af92.png)

We should support that because we also want to run several queries in sequence using this syntax.

**Comment by stoch** [comment]
Another example test case which runs in SqlNavigator is:

```
truncate table TEST;
insert into TEST(ITEM, VAL) values ('A', 'B');
select * from TEST;

```

**Comment by acautin** [comment]
@stoch this is working fine in current master dderl/sqlparse tested in our local db with:

```
TRUNCATE TABLE
    testtable;
INSERT INTO
    testtable (
        personid, lastname)
VALUES
    (1, 'a');
SELECT
    *
FROM
    testtable;
```
