### ISSUE TITLE
allow the system beep to be disabled per system

### ISSUE THREAD

**Issue by tgdriph3** [K2InformaticsGmbH/dderl#549]
Hi Bikram,
as bespoken with you on the phone. The system beep generated in DDerl on "no result" on SQL query hurts my ears every time it's played when wearing my headset. It would be good to have this system beep mutable per system over ddConfig.

Thanks & Regards Philippe

**Comment by c-bik** [comment]
@acautin Can you please replace this feature with visual aid (css color transition animation etc), or remove it all togather (into a branch)!

**Comment by acautin** [comment]
Added small icon as visual indication instead to make it more unobtrusive.

![bell](https://user-images.githubusercontent.com/949102/59056691-11b59f00-8899-11e9-82f9-a4211a7f1222.png)
