### ISSUE TITLE
CLOB support for oracle.

### ISSUE THREAD

**Issue by acautin** [K2InformaticsGmbH/dderl#554]
- [x] [Trying to query a table with a CLOB returns `error invalid-handle` when field is NULL](https://github.com/K2InformaticsGmbH/erloci/issues/65)
- [ ] [Non NULL CLOB fields can't be edited](https://github.com/K2InformaticsGmbH/erloci/issues/69) (see comment below for fix/workaround)

**Comment by acautin** [comment]
Closing this as it was a issue with the driver.  https://github.com/K2InformaticsGmbH/erloci/issues/65

**Comment by c-bik** [comment]
CLOB edits require special insert/update constructions in 
https://github.com/K2InformaticsGmbH/dderl/blob/4aba64791ea4dc65f3024d7a71ebd5729f0c3472/src/dderloci_stmt.erl#L157
and
https://github.com/K2InformaticsGmbH/dderl/blob/4aba64791ea4dc65f3024d7a71ebd5729f0c3472/src/dderloci_stmt.erl#L186
to wrap erlang binary with `to_clob(SQLT_STR)` in insert/update SQLs

Ref: https://github.com/K2InformaticsGmbH/erloci/issues/69#issuecomment-424916772

**Comment by acautin** [comment]
@c-bik moving reading in chunks into another issue as it is not in the current scope.
