### ISSUE TITLE
CSV View Names corrupted in 'Save View'

### ISSUE THREAD

**Issue by stoch** [K2InformaticsGmbH/dderl#567]
Saving a second time corrupts the name.

![image](https://user-images.githubusercontent.com/1941407/51541153-657a9b00-1e58-11e9-852b-ecfbebe81d9f.png)

**Comment by acautin** [comment]
fixed by https://github.com/K2InformaticsGmbH/dderl/commit/d260dd31622608cf5e6a07151fd91268099db9e6
