### ISSUE TITLE
node LTS upgrade blocked

### ISSUE THREAD

**Issue by c-bik** [K2InformaticsGmbH/dderl#571]
Due to [npm.community#1377](https://npm.community/t/unhelpful-error-message-when-publishing-without-logging-in-error-eperm-operation-not-permitted-unlink/1377/3) npm to latest node LTS upgrade fails!

![image](https://user-images.githubusercontent.com/913008/52214833-e8f1ae80-2892-11e9-8bb6-a780e5be67d3.png)

**Un reproducible in Windows 10 etc**

_Version 6.1.0 is by far tested OK_

**Comment by acautin** [comment]
Decided to move into yarn as it plays better with our setup. https://github.com/K2InformaticsGmbH/dderl/pull/580
