### ISSUE TITLE
008980 Add compare function to cell level menu.

### ISSUE THREAD

**Issue by acautin** [K2InformaticsGmbH/dderl#573]
It should be possible to select a pair of cells to compare its content. A call to the locally logged in imem should be performed of the form: ``imem_sec:term_diff(SKey,LeftType, LeftData, RightType, RightData)`` the result (list 5-tuples with the comparison by lines) will be of the form: 

``{ddTermDiff, id, left, cmp, right} ``

this list should then be mapped into a newly created fsm with 4 columns sent to the user: ```id, left, cmp, right``` with the status completed.

**Comment by stoch** [comment]
@acautin We are mainly comparing code here. This is the main purpose of the new diff function. That said, we would like to have the possibility (maybe in general) to switch between tow different renderings:
* html view (normal dderl rendering with compressed white space and hidden line breaks)
* fixed font view with all white space rendered (tabbing on 4 char lines)

Please create a new issue for this if it cannot be done in this one.
