### ISSUE TITLE
multiple SQL drop commands

### ISSUE THREAD

**Issue by stoch** [K2InformaticsGmbH/dderl#583]
Why does this not work?

Can we fix it?

![image](https://user-images.githubusercontent.com/1941407/53650126-1ccab480-3c44-11e9-8ff4-b68b197ef3a0.png)

**Comment by acautin** [comment]
@stoch parser doesn't support ``drop view`` query:

```
sqlparse:parsetree(<<"DROP VIEW SBS1_ADMIN.DT_BIH">>).
{parse_error,{"1: syntax error before: 'VIEW'",
              [{'DROP',1}, 
               {'VIEW',1},
               {'NAME',10,"SBS1_ADMIN"},
               {'.',1},
               {'NAME',6,"DT_BIH"},
               {';',1}]}}
```
We use the parser to determine multiple queries, otherwise we give the full string to oracle for processing.
