### ISSUE TITLE
Send/receive doesn't work for sender in tail mode.

### ISSUE THREAD

**Issue by acautin** [K2InformaticsGmbH/dderl#608]
Trying to send data obtained in tail mode to persist it in another table doesn't generate any rows for the receiver.

**Comment by acautin** [comment]
Unable to reproduce it locally, I can receive the data without any issues.
![Screenshot 2019-08-09 at 16 39 22](https://user-images.githubusercontent.com/949102/62787154-64434f80-bac4-11e9-9b83-96573e690976.png)

Please check the logs maybe there is some explanation there.

**Comment by stoch** [comment]
false alarm, probably due to incomplete data type support for pid()
