### ISSUE TITLE
009069 Background Color for DDerl Connections

### ISSUE THREAD

**Issue by stoch** [K2InformaticsGmbH/dderl#611]
DDerl connections must be given a class attribute during configuration with the use of a  drop_down selection of standard connection classes. Standard classes will be the following atoms (arbitrarily extensible by configuration):

* test
* mgmt
* stag
* inte
* prod

The picked class will be stored in ddConn.access (a map). 

ddConfig will give the list of possible classes (for the generation of a drop-down list in the connect popup) and backgroundColors for each class lookup.
The default config will be:

```
[{dderl,connectionClasses}]     [test,mgmt,stag,inte,prod]
[{dderl,backgroundColor},test]  <<"lightblue">>
[{dderl,backgroundColor},mgmt]  <<"#CDFECD">>
[{dderl,backgroundColor},stag]  <<"#FFFACD">>
[{dderl,backgroundColor},inte]  <<"rgb(220,220,160)">>
[{dderl,backgroundColor},prod]  <<"rgb(255,255,255)">>
[{dderl,backgroundColor}]       <<"rgb(220,220,220)">>
```

Possible values for backgroundColor are html color names or a strings as indicated above.

The backgroundColor value lookup will be used as background color for the connection.

**Comment by acautin** [comment]
Final configuration:

![image](https://user-images.githubusercontent.com/949102/63330715-92caf100-c334-11e9-831b-dcf66b97c4ba.png)

![image](https://user-images.githubusercontent.com/949102/63330745-a6765780-c334-11e9-958b-b949cbd5b518.png)
