### ISSUE TITLE
Problems with SQL Parameter Parsing

### ISSUE THREAD

**Issue by stoch** [K2InformaticsGmbH/dderl#617]
```sql
begin
    PKG_MTRAC_SMS.SEARCH_RECEIVER(
        :SQLT_DAT_START_DATE,
        :SQLT_DAT_END_DATE,
        :SQLT_STR_SENDER,
        :SQLT_STR_RECEIVER,
        :SQLT_STR_SHORTID,
        :SQLT_STR_GENERATED,
        :SQLT_INT_ROWLIMIT,
        :SQLT_RSET_OUT_RESULT
    );
end
```

![image](https://user-images.githubusercontent.com/1941407/64272917-9ff4fc00-cf40-11e9-8e18-e3027938c09d.png)

![image](https://user-images.githubusercontent.com/1941407/64273074-e185a700-cf40-11e9-92bd-8fff6ee91c08.png)

**Comment by c-bik** [comment]
@stoch the crash above is now fixed but the input you provided above is being rejected by DB now:
![image](https://user-images.githubusercontent.com/913008/64321234-74195b00-cfc0-11e9-892b-e78268de6162.png)
Please verify
