### ISSUE TITLE
SBS Query Import Error (SBS0/AAAPROVWS-MBUDGET-SESSION.QEF)

### ISSUE THREAD

**Issue by c-bik** [K2InformaticsGmbH/dderl#65]
Query:
```
SELECT SIC_MSISDN, SIC_IMSI, SIC_PAYMENT_METHOD, SIC_STYPE, SIC_DUOCARD,
SIC_DUAL_MSISDN, SIC_DUAL_IMSI, SIC_ENTRY_DATE, SIC_VALID_DATE,
SIC_TRANSFER_DATE, SIC_CHANGE_DATE, SIC_SYNC_DATE, SIC_ESID, SIC_STATUS,
SIC_PAYMENT_TYPE, SIC_USER_LANGUAGE, SIC_BIRTHDATE, SIC_MAIN_SEGMENT,
SIC_BIRTHDATE_STATUS, SIC_BARRING_STATE, SIC_CUSTOMER_ID, SIC_COMPANY_ID,
SIC_TOP_LEVEL_COMPANY_ID, SIC_FINE_SEGMENT, SIC_SERVICE_NUMBER, SIC_BRAND,
SIC_MODEL, SIC_REFRESH_TYPE, SIC_CHANGECOUNT
FROM SBS0_ADMIN.SICACHE
WHERE
SIC_PAYMENT_METHOD = 5 AND SIC_ENTRY_DATE >= sysdate -1/96
ORDER BY
SIC_ENTRY_DATE, SIC_ENTRY_DATE, SIC_ENTRY_DATE DESC, SIC_ENTRY_DATE DESC,
SIC_ENTRY_DATE, SIC_ENTRY_DATE DESC, SIC_ENTRY_DATE, SIC_ENTRY_DATE DESC
```

Error:
07:22:48.529 [warning] {ddLog,{1384,323768,531000},warning,<0.418.0>,imem_sql,sort_fun_item,524,'dderl@host',[{ex,'ClientError'},<<"SIC_ENTRY_DATE">>],<<"Bad sort expression">>,[{imem_sql,'-sort_fun_item/3-fun-1-',1,[{file,"src/imem_sql.erl"},{line,524}]},{imem_sql,'-build_sort_fun/2-lc$^0/1-1-',2,[{file,"src/imem_sql.erl"},{line,480}]},{imem_sql,build_sort_fun,2,[{file,"src/imem_sql.erl"},{line,480}]},{dderloci,build_sort_fun,2,[{file,"src/dderloci.erl"},{line,135}]},{dderloci,exec,2,[{file,"src/dderloci.erl"},{line,58}]},{oci_adapter,process_query,2,[{file,"src/oci_adapter.erl"},{line,527}]},{oci_adapter,process_cmd,5,[{file,"src/oci_adapter.erl"},{line,207}]}]}
07:22:48.529 [error] [_DDRL_] {dderl_session,287} Problem processing command: throw:{'ClientError',{"Bad sort expression",<<"SIC_ENTRY_DATE">>}}
[{imem_sql,'-sort_fun_item/3-fun-1-',1,[{file,"src/imem_sql.erl"},{line,524}]},{imem_sql,'-build_sort_fun/2-lc$^0/1-1-',2,[{file,"src/imem_sql.erl"},{line,480}]},{imem_sql,build_sort_fun,2,[{file,"src/imem_sql.erl"},{line,480}]},{dderloci,build_sort_fun,2,[{file,"src/dderloci.erl"},{line,135}]},{dderloci,exec,2,[{file,"src/dderloci.erl"},{line,58}]},{oci_adapter,process_query,2,[{file,"src/oci_adapter.erl"},{line,527}]},{oci_adapter,process_cmd,5,[{file,"src/oci_adapter.erl"},{line,207}]},{dderl_session,process_call,4,[{file,"src/dderl_session.erl"},{line,285}]}]

**Comment by acautin** [comment]
Not reproducible anymore.
