### ISSUE TITLE
Histogramming with multiple columns

### ISSUE THREAD

**Issue by stoch** [K2InformaticsGmbH/dderl#79]
Enhancement proposal with little priority:

Selecting more than one column and asking for a histogram could combine the selected columns (in possibly re-arranged view order left to right) into tuples of string values as keys 

![2015-05-11 12_00_11-zhhapmop-sbsm01 it bwns ch - remote desktop connection - __remote](https://cloud.githubusercontent.com/assets/1941407/7562563/b166a246-f7d5-11e4-9603-e440224b042a.jpg)

The key header could be shown as  "BD_BIHID,BD_MSISDN_A" (instead of "BD_MSISDN_A")
and the key data as "0949694219,41796314151"  (instead of "41796314151")
but internally the key would really be  {<<""0949694219">>,<<"41796314151">>}
and also sort like that.

**Comment by c-bik** [comment]
@stoch Merged to master https://github.com/K2InformaticsGmbH/dderl/pull/163 related to this issue, please verify and comment/close.

**Comment by walter-weinmann** [comment]
This could be closed?
