### ISSUE TITLE
DDerl node label / version missing after re-connect 

### ISSUE THREAD

**Issue by stoch** [K2InformaticsGmbH/dderl#93]
The part with green frame gets lost after re-connecting to another database.

![2015-06-17 19_13_42-zhhapmop-sbsm01 it bwns ch - remote desktop connection - __remote](https://cloud.githubusercontent.com/assets/1941407/8213856/55384638-1525-11e5-90b9-bab642814b7e.jpg)

**Comment by c-bik** [comment]
Unable to reproduce!
