### ISSUE TITLE
Opening a saved view should stay inside the visible screen.

### ISSUE THREAD

**Issue by acautin** [K2InformaticsGmbH/dderl#97]
We should override (without saving back) the position and height of a saved view if it is opened on a smaller screen.

Update: After discussion with @stoch it was decided the height should be adjusted as we can always show less rows but the width should be left for automatic scrolling.

**Comment by c-bik** [comment]
@acautin can we close this one?

**Comment by acautin** [comment]
@c-bik well I still want to improve the positioning of the windows maybe remove the milestone and we leave it there for hackergarten ?.

**Comment by c-bik** [comment]
Ok milestone removed!
