### ISSUE TITLE
badarg for inline view

### ISSUE THREAD

**Issue by stoch** [K2InformaticsGmbH/dderl#98]
The following results in a badarg when executed against the SBS1_ADMIN schema:

select BD_MSISDN_A, BD_MSISDN_B FROM (
select /*+ NO_INDEX (BDETAIL1) */ BD_MSISDN_A, BD_MSISDN_B from BDETAIL1 where ROWNUM <= :SQLT_INT_ROWLIMIT and bd_datetime >= :SQLT_DAT_START_DATE and bd_datetime <= :SQLT_DAT_END_DATE and BD_CONSOLIDATION like :SQLT_STR_SHORTID and (:SQLT_STR_GENERATED is null or NVL(BD_GENERATED, 0) like :SQLT_STR_GENERATED) group by bd_msisdn_a, bd_msisdn_b )

**Comment by c-bik** [comment]
@stoch Please provide related rows/info from ddLog and dderlLog

**Comment by stoch** [comment]
This dowes not happen any more. Seems to be fixed by some other changes.
